### ISSUE TITLE
Does cornflakes support complicated pointer based data-structures?

### ISSUE THREAD

**Issue by Funlxy** [deeptir18/cornflakes#7]
Cornflakes is a really good job. But I'm wonder if it supports complex pointer-based data structures(like tree)?

The tree structure in the code seems to be a fixed shape tree, where fields are not pointers. If they were pointers would they still be able to be serialised/deserialised properly?

**Comment by deeptir18** [comment]
Thanks for your interest.
Cornflakes is based on the protobuf IDL data structure, and,
As far as I know, it is not possible to express trees with pointers in this IDL itself (which is why we had the fixed depth tree in the example source code). Therefore, as you have pointed out, Cornflakes can't handle pointer based data structures automatically.

**Comment by Funlxy** [comment]
> Thanks for your interest. Cornflakes is based on the protobuf IDL data structure, and, As far as I know, it is not possible to express trees with pointers in this IDL itself (which is why we had the fixed depth tree in the example source code). Therefore, as you have pointed out, Cornflakes can't handle pointer based data structures automatically.

Thank you!
